name: Test

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version to be released (e.g. 2.3.0).'
        required: true

jobs:
  do-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: deploy file to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: 'kwart'
          server: 'frs.sourceforge.net'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './distribution/licenses/*'
          remote_path: /home/frs/project/jsignpdf/test
          sftpArgs: '-o ConnectTimeout=5'
          sftp_only: true
